[package]
name = "modrinth_downloader"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ureq = "2.6"
toml = "0.5"
sha2 = "0.10"
hex = "0.4"
serde_json = "1.0"
serde = {version = "1.0", features = ["serde_derive"]}
env_logger = "0.10"
log = "0.4"