# Path where the mods should be downloaded
mod_path = "./mods"

# Game version for mods
version = "1.19.3"

# Loader
loader = "fabric"

# Examples
mod_ids = [
  "lithium",
  "ferrite-core",
  "starlight",
  "krypton",
]