# Path where the mods should be downloaded
mod_path = "/minecraft/mods"

# Game version for mods
version = "1.19.3"

# Loader
loader = "fabric"

mod_ids = [
  # This uses the ID of the mod
  "gvQqBUqZ", # Lithium
  # You can also use the slug of the mod. eg. https://modrinth.com/mod/ferrite-core <- this is the important part
  "ferrite-core", # FerriteCore
]
