name: Build Release
on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CARGO_REGISTRIES_CRATES_IO_PROTOCOL: "sparse"
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
      - name: Install cross
        run: |
          cargo install cross --git https://github.com/cross-rs/cross
      - name: Install musl-tools
        run: |
          sudo apt-get install musl-tools -y

      - uses: Swatinem/rust-cache@v2

      - name: Build project x86_64
        run: |
          cross build --release --target x86_64-unknown-linux-musl
      
      - name: Build project aarch64
        run: |
          cross build --release --target aarch64-unknown-linux-musl