name: Build Release
on:
  push:
    tags: ["*"]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CARGO_REGISTRIES_CRATES_IO_PROTOCOL: "sparse"
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-unknown-linux-musl
      - name: Install musl-tools
        run: |
          sudo apt-get install musl-tools -y

      - uses: Swatinem/rust-cache@v2

      - name: Build project
        run: |
          cargo build --release --target=x86_64-unknown-linux-musl

      - uses: softprops/action-gh-release@v1
        with:
          files: |
            target/x86_64-unknown-linux-musl/release/modrinth-downloader