name: Build Release
on:
  push:
    tags: ["*"]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CARGO_REGISTRIES_CRATES_IO_PROTOCOL: "sparse"
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - uses: Swatinem/rust-cache@v2
      - uses: dtolnay/rust-toolchain@stable
      - name: Install cross
        run: |
          cargo install cross --git https://github.com/cross-rs/cross
      - name: Build project x86_64
        run: |
          cross build --release --target x86_64-unknown-linux-musl

      - uses: softprops/action-gh-release@v1
        with:
          files: |
            target/x86_64-unknown-linux-musl/release/modrinth-downloader
            target/aarch64-unknown-linux-musl/release/modrinth-downloader